class Phrase < Formula
  desc "Experimental Phrase CLI Tool - API client binary"
  homepage "https://phrase.com/cli"
  GITHUB_URL = "https://github.com/phrase/phrase-cli/releases/download".freeze

  version "2.0.0"
  if OS.linux?
    if OS.respond_to?(:bits) && OS.bits == 32
      sha256 "370d13982cb926835ed5865c03ff93811efc1c37a3e3ecf6741d28ca8d35d39a"
      url "#{GITHUB_URL}/#{version}/phrase_linux_386.tar.gz"
    else
      sha256 "6b68461195de87414d824fff799790503dab3ade5af21fe4d4f80f6ae2466aa0"
      url "#{GITHUB_URL}/#{version}/phrase_linux_amd64.tar.gz"
    end
  else
    sha256 "a737c83a0cd5202c4676e7e74b16c9221282219dc566539fff85e9c1f689f97a"
    url "#{GITHUB_URL}/#{version}/phrase_macosx_amd64.tar.gz"
  end

  def install
    warning = <<~EOM
      This is experimental CLI for Phrase generated by the OpenAPI Generator from OpenAPI documents.
      Visit https://github.com/phrase/phrase-cli for more details

      THIS IS NOT PRODUCTION READY!

      If you are looking for stable release please use `brew install phraseapp`
    EOM

    system "mv phrase* phrase"
    bin.install "phrase"
    opoo warning
  end

  test do
    output = shell_output("#{bin}/phrase version 2>&1", 64)
    assert_match version, output
  end
end
